//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstateMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListingPicture
    {
        public long ImageID { get; set; }
        public string ImagePath { get; set; }
        public string ImageAlt { get; set; }
        public long ListingID { get; set; }
    
        public virtual Listing Listing { get; set; }
    }
}
